### ISSUE TITLE
Difficult to replicate the results

### ISSUE THREAD

**Issue by nixingyang** [TencentYoutuResearch/PersonReID-YouReID#1]
Thanks for publishing the code.
After putting some effort, I still find it difficult to replicate the results. For example, no script is available to "Prepare Datasets", and one has to implement his/her own. It would be good if a foolproof step-by-step guide could be provided, especially for the training procedure.
I have completed the training on Market-1501. However, the reported mAP score is 0.06245. I have made substantial modifications, so there might be bugs in my own script. Could you please check the attached [slurm-xxx.log](https://github.com/TencentYoutuResearch/PersonReID-CACENET/files/5860640/slurm-xxx.log) for training? It looks like that the training collapsed.
All the best.

**Comment by poorfriend** [comment]
> 

> Thanks for publishing the code.
> After putting some effort, I still find it difficult to replicate the results. For example, no script is available to "Prepare Datasets", and one has to implement his/her own. It would be good if a foolproof step-by-step guide could be provided, especially for the training procedure.
> I have completed the training on Market-1501. However, the reported mAP score is 0.06245. I have made substantial modifications, so there might be bugs in my own script. Could you please check the attached [slurm-xxx.log](https://github.com/TencentYoutuResearch/PersonReID-CACENET/files/5860640/slurm-xxx.log) for training? It looks like that the training collapsed.
> All the best.

Sorry for the bad experience. We will add a script for preparing data.sh soon.
I see the losses don't converge from your log, maybe because the model was trained from scratch, not from a pre-trained model from ImageNet.
our pre-trained model is converted from torch official model, we will also release the conversion script and converted pre-trained model soon.

**Comment by poorfriend** [comment]
> Thanks for publishing the code.
> After putting some effort, I still find it difficult to replicate the results. For example, no script is available to "Prepare Datasets", and one has to implement his/her own. It would be good if a foolproof step-by-step guide could be provided, especially for the training procedure.
> I have completed the training on Market-1501. However, the reported mAP score is 0.06245. I have made substantial modifications, so there might be bugs in my own script. Could you please check the attached [slurm-xxx.log](https://github.com/TencentYoutuResearch/PersonReID-CACENET/files/5860640/slurm-xxx.log) for training? It looks like that the training collapsed.
> All the best.

we add some scripts,  formatted dataset,  pretrained model and train log,  you can try again. If you have any other questions, please feel free to ask.

**Comment by nixingyang** [comment]
Thanks for the patches. I managed to obtain the following results:

| Dataset | mAP | rank-1 |
| - | - | - |
| Market1501 | 0.8968 | 0.9513 |
| DukeMTMC_reID | 0.8137 | 0.9088 |
| MSMT17 | 0.6176 | 0.8310 |
