### ISSUE TITLE
enviroment configuration

### ISSUE THREAD

**Issue by dulvqingyun** [TencentYoutuResearch/PersonReID-YouReID#3]
Thanks for your excellent work and code. But when i try to replicate the results, i encounter a runtime error:
F tensorflow/core/framework/tensor.cc:624] Check failed: dtype() == expected_dtype (10 vs. 3) int32 expected, got bool

my environment is:  python == 3.7.1 tensorflow == 1.14.0
Could you tell your environment  that can run the training?

**Comment by poorfriend** [comment]
> Thanks for your excellent work and code. But when i try to replicate the results, i encounter a runtime error:
> F tensorflow/core/framework/tensor.cc:624] Check failed: dtype() == expected_dtype (10 vs. 3) int32 expected, got bool
> 
> my environment is: python == 3.7.1 tensorflow == 1.14.0
> Could you tell your environment that can run the training?

I use python==3.6 and tensorflow==1.13.0

**Comment by dulvqingyun** [comment]
> 
> 
> > Thanks for your excellent work and code. But when i try to replicate the results, i encounter a runtime error:
> > F tensorflow/core/framework/tensor.cc:624] Check failed: dtype() == expected_dtype (10 vs. 3) int32 expected, got bool
> > my environment is: python == 3.7.1 tensorflow == 1.14.0
> > Could you tell your environment that can run the training?
> 
> I use python==3.6 and tensorflow==1.13.0

Thanks for your reply, i downgrade tensorflow to 1.13.1 and it works.
