### ISSUE TITLE
when to get the best model

### ISSUE THREAD

**Issue by sophieyl** [TencentYoutuResearch/PersonReID-YouReID#5]
hi~
I observe that the code save the checkpoint file at the end of the epoch 80, 
then it achieve the best performance without testing in the training process.
If I need to use other dataset, I should modify the code to do testing in the training process,
in order to know when should be stop. Am I right ?

**Comment by poorfriend** [comment]
> hi~
> I observe that the code save the checkpoint file at the end of the epoch 80,
> then it achieve the best performance without testing in the training process.
> If I need to use other dataset, I should modify the code to do testing in the training process,
> in order to know when should be stop. Am I right ?
Yes， Maybe epoch 80 is not the best checkpoint.  I use the lastest checkpoint for simplicity.

**Comment by poorfriend** [comment]
> hi~
> I observe that the code save the checkpoint file at the end of the epoch 80,
> then it achieve the best performance without testing in the training process.
> If I need to use other dataset, I should modify the code to do testing in the training process,
> in order to know when should be stop. Am I right ?

Yes， Maybe epoch 80 is not the best checkpoint. I use the lastest checkpoint for simplicity.
